name: Master

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build Info
        run: |
          git config user.name "Automation for master branch"

      - name: Install
        run: |
          yarn install --pure-lockfile
          yarn run build

      - name: Test
        run: yarn run test
        env:
          CI: true

      - name: Generate Deploy
        run: |
          echo "Creating deploy commit for gh pages branch"
          git fetch
          yarn run create-deploy

      - name: Push Deploy
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
